version: '3'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "30000:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  cassandra:
    image: cassandra:latest
    restart: always
    ports:
      - "30001:9042"
      - "30002:9160"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  mariadb_data:
  cassandra_data:
